using NUnit.Framework;

namespace AdventOfCode2024.Day8.Tests;

public static class SolutionDay8Tests
{
	[Test]
	public static void Part1()
	{
		var input =
			"""
			............
			........0...
			.....0......
			.......0....
			....0.......
			......A.....
			............
			............
			........A...
			.........A..
			............
			............
			""";

		Assert.That(SolutionDay8.RunPart1([.. input.Split(Environment.NewLine)]), Is.EqualTo(14));
	}

	[Test]
	public static void Part2()
	{
		var input =
			"""
			............
			........0...
			.....0......
			.......0....
			....0.......
			......A.....
			............
			............
			........A...
			.........A..
			............
			............
			""";

		Assert.That(SolutionDay8.RunPart2([.. input.Split(Environment.NewLine)]), Is.EqualTo(34));
	}
}